routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
  return view('login');
});

Route::resource('auth', 'App\Http\Controllers\AuthController');
Route::middleware(['auth', 'isAdmin:1,0'])->group(function () {

  Route::prefix('menu/')->group(function () {
    Route::resource('home', 'App\Http\Controllers\DashboardController');
    Route::resource('profile', 'App\Http\Controllers\ProfileController');
    Route::resource('penarikan_barang', 'App\Http\Controllers\PenarikanBarangController');
    Route::resource('pengajuan_barang', 'App\Http\Controllers\PengajuanBarangController');

    Route::prefix('master_data/')->group(function () {
      Route::resource('produk', 'App\Http\Controllers\ProdukController');
      Route::resource('barang', 'App\Http\Controllers\BarangController');
      Route::resource('pemasok', 'App\Http\Controllers\PemasokController');
      Route::resource('pelanggan', 'App\Http\Controllers\PelangganController');
    });

    Route::prefix('transaksi/')->group(function () {
      Route::resource('pembelian', 'App\Http\Controllers\PembelianController');
      Route::resource('penjualan', 'App\Http\Controllers\PenjualanController');
    });

    Route::prefix('laporan/')->group(function () {
      Route::resource('laporan_pembelian', 'App\Http\Controllers\LaporanPembelianController');
      Route::resource('laporan_penjualan', 'App\Http\Controllers\LaporanPenjualanController');
    });

    Route::get('logout', function () {
      Auth::logout();
      return redirect('auth');
    });
  });

  Route::prefix('admin/user_manage/')->group(function () {
    Route::middleware(['isAdmin:1'])->group(function () {
      Route::resource('account', 'App\Http\Controllers\UserController');
      Route::resource('access', 'App\Http\Controllers\AccessController');
    });
  });
});

app/Models/Pelanggan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Pelanggan extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($post) {
            $post->{$post->getKeyName()} = (string) Str::uuid();
        });
    }

    public function getIncrementing()
    {
        return false;
    }

    public function getKeyType()
    {
        return 'string';
    }

    protected $fillable = [
        'kode_pelanggan', 'nama', 'alamat', 'no_telp', 'email', 'user_id'
    ];
}

app/Http/Controllers/PelangganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\str;

use App\Models\Pelanggan;
use App\Models\Acces;
use Yajra\DataTables\DataTables;

class PelangganController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index(Request $request)
  {
    $checkAccess = Acces::where('user_id', Auth::id())->first();
    if ($checkAccess->kelola_penjualan == 1 && Auth::check() == true) {
      $lastId = Pelanggan::select('kode_pelanggan')->orderBy('kode_pelanggan', 'desc')->first();
      $kode = ($lastId == null ? 'M0000001' : sprintf('M%07d', substr($lastId->kode_pelanggan, 1) + 1));

      if ($request->ajax()) {
        $pelanggan = DB::table(DB::raw('pelanggans, (SELECT @rownum := 0) r'))
          ->select('pelanggans.*', DB::raw('@rownum := @rownum + 1 AS rownum'))->where('kode_pelanggan', '!=', 'M0000000')->get();
        return DataTables::of($pelanggan)
          ->addColumn('action', function ($row) {
            $btn = '<div class="dropdown d-inline">';
            $btn = $btn . '<button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Manage</button>';
            $btn = $btn . '<div class="dropdown-menu" x-placement="bottom-start" will-change: transform;">';
            $btn = $btn . '<a class="dropdown-item has-icon editPelanggan" href="javascript:void(0)"  data-id="' . $row->id . '" data-kode_pelanggan="' . $row->kode_pelanggan . '"data-nama="' . $row->nama . '" data-alamat="' . $row->alamat . '" data-no_telp="' . $row->no_telp . '" data-email="' . $row->email . '"><i class="far fa-edit"></i> Edit</a>';
            $btn = $btn . '<a class="dropdown-item has-icon deletePelanggan" href="javascript:void(0)" data-id="' . $row->id . '" data-nama="' . $row->nama . '" ><i class="fas fa-trash"></i> Hapus</a>';
            $btn = $btn . '</div>';
            $btn = $btn . '</div>';
            return $btn;
          })
          ->rawColumns(['action'])
          ->make(true);
      }
      return view('pelanggan.index')->with(['title' => "Pelanggan", 'kode' => $kode]);
    } else {
      return back();
    }
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $checkAccess = Acces::where('user_id', Auth::id())->first();
    if ($checkAccess->kelola_penjualan == 1 && Auth::check() == true) {
      if (empty($request->id)) {
        $check_kode_pelanggan = Pelanggan::where('kode_pelanggan', $request->kode_pelanggan)->count();
        $check_email_pelanggan = Pelanggan::where('email', $request->email)->count();
        if ($check_kode_pelanggan != 0) {
          return response()->json(['icon' => 'error', 'title' => 'Create Fail', 'message' => 'Kode Pelanggan sudah tersedia harap refresh terlebih dahulu', 401]);
        } elseif ($check_email_pelanggan != 0) {
          return response()->json(['icon' => 'error', 'title' => 'Create Fail', 'message' => 'Email Sudah Digunakan', 401]);
        } else {
          $pelanggan = new Pelanggan;
          $pelanggan->id = Str::uuid();
          $pelanggan->kode_pelanggan = $request->kode_pelanggan;
          $pelanggan->nama = $request->nama;
          $pelanggan->alamat = $request->alamat;
          $pelanggan->no_telp = $request->no_telp;
          $pelanggan->email = $request->email;
          $pelanggan->save();
          return response()->json(['title' => 'Create Success', 'message' => 'Data Berhasil Disimpan', 200]);
        }
      } else {
        $check_id_pelanggan = Pelanggan::find($request->id);
        $check_email_pelanggan = Pelanggan::where('email', $request->email)->count();
        if ($check_email_pelanggan != 0 && $check_id_pelanggan->email != $request->email) {
          return response()->json(['icon' => 'error', 'title' => 'Edit Fail', 'message' => 'Email Sudah Digunakan', 401]);
        } else {
          $pelanggan = Pelanggan::where('id', $request->id)->update($request->all());
          return response()->json(['title' => 'Edit Success', 'message' => 'Data Berhasil Diubah', 200]);
        }
      }
    } else {
      return back();
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $checkAccess = Acces::where('user_id', Auth::id())->first();
    if ($checkAccess->kelola_penjualan == 1 && Auth::check() == true) {
      Pelanggan::find($id)->delete();
      return response()->json(['title' => 'Delete Success', 'message' => 'Data Berhasil Dihapus', 200]);
    } else {
      return back();
    }
  }
}

resources/views/pelanggan/index.blade.php
@extends('templates/master')
@section('content')

<div class="section-header">
  <h1>{{ $title }}</h1>
  <div class="section-header-button">
    <a href="javascript:void(0)" id="tombol-tambah" class="btn btn-primary"><i class="fas fa-plus-circle mr-1"></i>Data Pelanggan</a>
  </div>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item active">Menu</div>
    <div class="breadcrumb-item">Data Master</div>
    <div class="breadcrumb-item"><a href="javascript:void(0)">{{ $title }}</a></div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover" id="data-table" style="width:100%">
              <thead class="text-dark bg-light">
                <tr>
                  <th>No</th>
                  <th>Kode Pelanggan</th>
                  <th>Nama</th>
                  <th>Alamat</th>
                  <th>Telp</th>
                  <th>Email</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody class="text-dark"></tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection
@section('scripts')
<script src="{{ asset('js/cleave.min.js') }}"></script>
<script src="{{ asset('js/cleave-phone.id.js') }}"></script>
@include('pelanggan/modal')
<script>
  $(document).ready(function() {
    $('#Pelanggan_sidebar').parent().addClass('active');
    $('#Pelanggan_sidebar').parent().parent().parent().addClass('active');

    let cleavePN = new Cleave('.phone-number', {
      phone: true,
      phoneRegionCode: 'id'
    });

    $(function() {
      $.ajaxSetup({
        headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
      });
      let table = $('#data-table').DataTable({
        processing: true,
        serverSide: true,
        responsive: true,
        ajax: "{{ route('pelanggan.index') }}",
        columns: [{
            data: 'rownum',
            name: 'rownum',
            searchable: false
          },
          {
            data: 'kode_pelanggan',
            name: 'kode_pelanggan'
          },
          {
            data: 'nama',
            name: 'nama'
          },
          {
            data: 'alamat',
            name: 'alamat'
          },
          {
            data: 'no_telp',
            name: 'no_telp'
          },
          {
            data: 'email',
            name: 'email'
          },
          {
            data: 'action',
            name: 'action',
            orderable: false,
            searchable: false
          },
        ],
      });

      $('#tombol-tambah').click(function() {
        $('#button-simpan').val("create-post");
        $('#Id').val('');
        $('#form-tambah-edit').trigger("reset");
        $('#myModalLabel').text("Tambah Pelanggan");
        $('#tambah-edit-modal').modal('show');
      });

      if ($("#form-tambah-edit").length > 0) {
        $("#form-tambah-edit").validate({
          messages: {
            nama: "Nama Pemasok tidak boleh kosong",
            alamat: {
              required: "Alamat tidak boleh kosong",
              minlength: "Alamat harus berisi Jl. No, Kota",
            },
            email: {
              required: "Email tidak boleh kosong",
              email: "Alamat email salah",
            },
            no_telp: {
              required: "Telp tidak boleh kosong",
              minlength: "Telp minimal 8 digit",
            },
          },
          errorPlacement: function(error, element) {
            let name = element.attr("name");
            $("#" + name + "_error").html(error);
          },

          submitHandler: function(form) {
            $('#tombol-simpan').html('Mengirim..');

            $.ajax({
              data: $('#form-tambah-edit').serialize(),
              url: "{{ route('pelanggan.store') }}",
              type: "POST",
              dataType: 'json',
              success: function(response) {
                $('#tombol-simpan').html('Simpan');
                if (response.icon == 'error') {
                  $('#tambah-edit-modal').modal('show');
                  iziToast.error({
                    title: response.title,
                    message: response.message,
                    position: 'topRight',
                  });
                } else {
                  $('#form-tambah-edit').trigger("reset");
                  $('#tambah-edit-modal').modal('hide');
                  table.draw();
                  iziToast.success({
                    title: response.title,
                    message: response.message,
                    position: 'topRight',
                  });
                }
              },
              error: function(response) {
                console.log('Error:', response);
                $('#tombol-simpan').html('Simpan');
              }
            });
          }
        });
      }

      $(document).on('click', '.editPelanggan', function() {
        $('#myModalLabel').text("Edit Pelanggan");
        $('#tombol-simpan').val("edit-post");
        $('#tambah-edit-modal').modal('show');

        let id = $(this).attr("data-id");
        let kode_pelanggan = $(this).attr("data-kode_pelanggan");
        let nama = $(this).attr("data-nama");
        let alamat = $(this).attr("data-alamat");
        let no_telp = $(this).attr("data-no_telp");
        let email = $(this).attr("data-email");

        $('.modal-body #Id').val(id);
        $('.modal-body #Kode_pelanggan').val(kode_pelanggan);
        $('.modal-body #nama').val(nama);
        $('.modal-body #Alamat').val(alamat);
        $('.modal-body #No_telp').val(no_telp);
        $('.modal-body #Email').val(email);

      });

      $(document).on('click', '.deletePelanggan', function() {
        let id = $(this).attr("data-id");
        let nama = $(this).attr("data-nama");
        iziToast.question({
          timeout: 20000,
          close: false,
          overlay: true,
          displayMode: 'once',
          id: 'question',
          zindex: 999,
          title: 'Yakin?',
          message: 'Data "' + nama + '" akan terhapus.',
          position: 'center',
          buttons: [
            ['<button><b>Ya, </b>Hapus</button>', function(instance, toast) {

              $.ajax({
                type: "DELETE",
                url: "{{ route('pelanggan.store') }}/" + id,
                success: function(response) {
                  table.draw();
                  iziToast.success({
                    title: response.title,
                    message: response.message,
                    position: 'topRight',
                  });
                },
                error: function(response) {
                  console.log('Error:', response);
                  $('#tombol-simpan').html('Simpan');
                }
              });

              instance.hide({
                transitionOut: 'fadeOut'
              }, toast, 'button');

            }, true],
            ['<button>Batal</button>', function(instance, toast) {

              instance.hide({
                transitionOut: 'fadeOut'
              }, toast, 'button');

            }],
          ],
        });

      });

    });
  });
</script>

@endsection

resources/views/pelanggan/modal.blade.php
<div class="modal fade" id="tambah-edit-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" class="needs-validation" novalidate="" id="form-tambah-edit" name="form-tambah-edit">
          <input type="hidden" name="id" id="Id" value="">
          <div class="form-row">
            <div class="form-group col-md-4">
              <label for="Kode_pelanggan">Kode Pelanggan <span class="text-danger">*</span></label>
              <input id="Kode_pelanggan" type="text" class="form-control" name="kode_pelanggan" value="{{ $kode }}" readonly>
            </div>
            <div class="form-group col-md-8">
              <label for="nama">Nama <span class="text-danger">*</span></label>
              <input id="nama" type="text" class="form-control" name="nama" tabindex="1" maxlength="20" required autofocus>
              <div class="invalid-feedback" id="nama_error"></div>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="Email">Email <span class="text-danger">*</span></label>
              <input id="Email" type="email" class="form-control" name="email" tabindex="2" required>
              <div class="invalid-feedback" id="email_error"></div>
            </div>
            <div class="form-group col-md-6">
              <label>No.Telephone <span class="text-danger">*</span></label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <div class="input-group-text">
                    <i class="fas fa-phone"></i>
                  </div>
                </div>
                <input type="text" class="form-control phone-number" id="No_telp" name="no_telp" tabindex="3" required>
                <div class="invalid-feedback" id="no_telp_error" style="margin-left: 55px;"></div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="Alamat">Alamat <span class="text-danger">*</span></label>
            <textarea id="Alamat" type="text" class="form-control" name="alamat" tabindex="4" minlength="10" maxlength="30" required></textarea>
            <div class="invalid-feedback" id="alamat_error"></div>
          </div>

      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary btn-block" id="tombol-simpan" tabindex="5">Simpan</button>
        <button type="submit" class="btn btn-light" data-dismiss="modal">Close</button>
      </div>
      </form>
    </div>
  </div>
</div>