routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
  return view('login');
});

Route::resource('auth', 'App\Http\Controllers\AuthController');
Route::middleware(['auth', 'isAdmin:1,0'])->group(function () {

  Route::prefix('menu/')->group(function () {
    Route::resource('home', 'App\Http\Controllers\DashboardController');
    Route::resource('profile', 'App\Http\Controllers\ProfileController');
    Route::resource('penarikan_barang', 'App\Http\Controllers\PenarikanBarangController');
    Route::resource('pengajuan_barang', 'App\Http\Controllers\PengajuanBarangController');

    Route::prefix('master_data/')->group(function () {
      Route::resource('produk', 'App\Http\Controllers\ProdukController');
      Route::resource('barang', 'App\Http\Controllers\BarangController');
      Route::resource('pemasok', 'App\Http\Controllers\PemasokController');
      Route::resource('pelanggan', 'App\Http\Controllers\PelangganController');
    });

    Route::prefix('transaksi/')->group(function () {
      Route::resource('pembelian', 'App\Http\Controllers\PembelianController');
      Route::resource('penjualan', 'App\Http\Controllers\PenjualanController');
    });

    Route::prefix('laporan/')->group(function () {
      Route::resource('laporan_pembelian', 'App\Http\Controllers\LaporanPembelianController');
      Route::resource('laporan_penjualan', 'App\Http\Controllers\LaporanPenjualanController');
    });

    Route::get('logout', function () {
      Auth::logout();
      return redirect('auth');
    });
  });

  Route::prefix('admin/user_manage/')->group(function () {
    Route::middleware(['isAdmin:1'])->group(function () {
      Route::resource('account', 'App\Http\Controllers\UserController');
      Route::resource('access', 'App\Http\Controllers\AccessController');
    });
  });
});

resources/views/403.blade.php
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <link rel="icon" href="{{ asset('img/logo.jpg') }}">
  <title>Em &mdash; Error</title>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('css/style.css') }}" rel="stylesheet">
  <link href="{{ asset('css/components.css') }}" rel="stylesheet">

</head>

<body class="sidebar-gone">
  <div id="app">
    <section class="section">
      <div class="container">
        <div class="page-error">
          <div class="page-inner">
            <h1>403</h1>
            <div class="page-description">
              Anda tidak memiliki akses pada halaman ini.
            </div>
            <div class="page-search">
              <div class="mt-3">
                <a href="{{ url('menu/home') }}">Kembali ke Home</a>
              </div>
            </div>
          </div>
        </div>
        <div class="simple-footer">
          Copyright © {{ date('Y') }}
          <div class="bullet"></div> ElMarket
        </div>

      </div>
    </section>
  </div>

  <script src="{{ asset('js/bootstrap.min.js') }}"></script>
  <script src="{{ asset('js/jquery.nicescroll.min.js') }}"></script>
  <script src="{{ asset('js/moment.min.js') }}"></script>
  <script src="{{ asset('js/stisla.js') }}"></script>
  <script src="{{ asset('js/scripts.js') }}"></script>

</body>

</html>

resources/views/dashboard.blade.php
@extends('templates/master')
@section('content')

<div class="section-header">
  <h1>{{ $title }}</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item active">

    </div>
  </div>
</div>
<div class="section-body">
  <div class="row">
    <div class="col-lg-4 col-md-6 col-sm-6 col-12">
      <div class="card card-statistic-1">
        <div class="card-icon bg-primary">
          <i class="fas fa-hand-holding-usd"></i>
        </div>
        <div class="card-wrap">
          <div class="card-header">
            <h4>Pendapatan</h4>
          </div>
          <div class="card-body">
            <small class="font-weight-bold">@php
              $total_pendapatan = 0;
              foreach(App\Models\Penjualan::get() as $tp) {
              $total_pendapatan += $tp->total_bayar;
              }
              @endphp
              Rp. {{ number_format($total_pendapatan,0) }}</small>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4 col-md-6 col-sm-6 col-12">
      <div class="card card-statistic-1">
        <div class="card-icon bg-danger">
          <i class="fas fa-money-check"></i>
        </div>
        <div class="card-wrap">
          <div class="card-header">
            <h4>Pembelian</h4>
          </div>
          <div class="card-body">
            <small class="font-weight-bold">@php
              $total_pembelian = 0;
              foreach(App\Models\Pembelian::get() as $tp) {
              $total_pembelian += $tp->total;
              }
              @endphp
              Rp. {{ number_format($total_pembelian,0) }}</small>

          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4 col-md-6 col-sm-6 col-12">
      <div class="card card-statistic-1">
        <div class="card-icon bg-warning">
          <i class="fas fa-boxes"></i>
        </div>
        <div class="card-wrap">
          <div class="card-header">
            <h4>Barang</h4>
          </div>
          <div class="card-body">
            <small class="font-weight-bold">@php
              $jml_barang = count(App\Models\Barang::get());
              @endphp
              {{ $jml_barang }}</small>
          </div>
        </div>
      </div>
    </div>
    <!-- <div class="col-lg-4 col-md-6 col-sm-6 col-12">
      <div class="card card-statistic-1">
        <div class="card-icon bg-success">
          <i class="far fa-user"></i>
        </div>
        <div class="card-wrap">
          <div class="card-header">
            <h4>Pelanggan</h4>
          </div>
          <div class="card-body">
            <small class="font-weight-bold">@php
              $jml_pelanggan = count(App\Models\Pelanggan::get());
              @endphp
              {{ $jml_pelanggan }}</small>
          </div>
        </div>
      </div>
    </div> -->


  </div>
  <div class="row">
    <div class="col-lg-12 col-md-12 col-12 col-sm-12">
      <div class="card">
        <div class="card-header">
          <h4>Data Penjualan 30 Hari Terakhir</h4>
          <div class="card-header-action">
          </div>
        </div>
        <div class="card-body">
          <canvas id="myChart" height="100"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script src="{{ asset('js/chart.min.js') }}"></script>
<script>
  $(document).ready(function() {
    $('#Dashboard_sidebar').parent().addClass('active');

    let ctx = document.getElementById('myChart');
    let myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: [

        ],
        datasets: [{
            label: 'Pendapatan Perhari',
            data: [

            ],
            backgroundColor: 'RGB(44, 77, 240)',
            borderColor: 'RGB(44, 77, 240)',
            borderWidth: 2,
          },
          {
            label: 'Jumlah Transaksi',
            data: [

            ],
            backgroundColor: 'rgb(75, 192, 192)',
            borderColor: 'rgb(75, 192, 192)',
            borderWidth: 2,
          },
        ]
      },
      options: {
        plugins: {
          title: {
            display: false,

          },
          legend: {
            display: true,
          }
        },
        scales: {
          x: {
            beginAtZero: false
          },
          y: [{
            ticks: {
              callback: function(value, index, values) {
                if (parseInt(value) >= 1000) {
                  return 'Rp. ' + value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                } else {
                  return 'Rp. ' + value;
                }
              }
            }
          }],
        },
        tooltips: {
          callbacks: {
            label: function(tooltipItem) {
              return tooltipItem.yLabel;
            }
          }
        }
      }
    });

    let UpdateData = function() {
      $.ajax({
        url: "{{ route('home.create') }}",
        type: "GET",
        dataType: "Json",
        headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        },
        success: function(response) {
          myChart.data = {
            labels: response.labels,
            datasets: [{
                label: 'Pendapatan Perhari',
                data: response.pendapatan,
                backgroundColor: 'RGB(44, 77, 240)',
                borderColor: 'RGB(44, 77, 240)',
                borderWidth: 2,
              },
              {
                label: 'Jumlah Transaksi',
                data: response.jml_data,
                backgroundColor: 'rgb(75, 192, 192)',
                borderColor: 'rgb(75, 192, 192)',
                borderWidth: 2,
              },
            ]
          }
          myChart.update();
        },
        error: function(response) {
          console.log(response.pendapatan);
        }
      })
    }

    UpdateData();
    setInterval(() => {
      UpdateData();
    }, 2500);
  });
</script>


@endsection

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>ElMart &mdash; Login</title>

  <link rel="icon" href="{{ asset('img/logo.jpg') }}">
  <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('css/fontawesome/css/all.min.css') }}" rel="stylesheet">

  <link href="{{ asset('css/style.css') }}" rel="stylesheet">
  <link href="{{ asset('css/components.css') }}" rel="stylesheet">

  <link href="{{ asset('css/sweetalert2.min.css') }}" rel="stylesheet">
</head>

<body>
  <div id="app">
    <section class="section">
      <div class="container mt-5">
        <div class="row">
          <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="login-brand">
              <img src="{{ asset('img/logo.jpg') }}" alt="logo" width="60" class="shadow-light rounded-circle mr-3">
              <span style="font-size: 15px;">ElMart</span>
              <h5 class="mt-3">Point Of Sales</h5>
            </div>
            <div class="card card-primary" style="margin-top: -20px;">
              <div class="card-body">
                <form class="needs-validation" novalidate="" action="{{ route('auth.store') }}" method="post">
                  @csrf
                  <div class="form-group">
                    <label for="username">Username</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <div class="input-group-text">
                          <i class="fas fa-user"></i>
                        </div>
                      </div>
                      <input id="username" type="username" class="form-control" name="username" tabindex="1" required autofocus>
                      <div class="invalid-feedback" style="margin-left: 45px;">Username tidak boleh kosong!</div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="password" class="control-label">Password</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <div class="input-group-text">
                          <i class="fas fa-lock"></i>
                        </div>
                      </div>
                      <input id="password" type="password" class="form-control" name="password" tabindex="2" required>
                      <div class="invalid-feedback" style="margin-left: 45px;">Password tidak boleh kosong!</div>
                    </div>

                  </div>
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="3">
                      Login
                    </button>
                  </div>
                </form>
              </div>
            </div>

            <div class="simple-footer">
              Copyright © ElMart {{ date('Y') }}
            </div>

          </div>
        </div>
      </div>
    </section>
  </div>
  <script src="{{ asset('js/sweetalert2.min.js') }}"></script>
  <script src="{{ asset('js/jquery.min.js') }}"></script>
  <script src="{{ asset('js/bootstrap.min.js') }}"></script>
  <script src="{{ asset('js/stisla.js') }}"></script>
  <script src="{{ asset('js/scripts.js') }}"></script>

  <script>
    @if(Session('fail'))
    Swal.fire({
      title: 'Gagal',
      text: '{{ Session("fail") }}',
      icon: 'error',
    })
    @endif
  </script>
</body>

</html>

resources/views/profile.blade.php
@extends('templates/master')
@section('content')

<div class="section-header">
    <h1>{{ $title }}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active">Menu</div>
        <div class="breadcrumb-item"><a href="javascript:void(0)">Profile</a></div>
    </div>
</div>

<div class="section-body">
    <div class="row">
        <div class="col-md-5">
            <div class="card author-box card-primary">
                <div class="card-body">
                    <div class="author-box-left">
                        <img alt="image" src="{{ asset('img/default_profile.jpg') }}" class="rounded-circle author-box-picture">
                    </div>
                    <div class="author-box-details">
                        <div class="author-box-name">
                            <a href="javascript:void(0)">{{ Auth::user()->nama }}</a>
                        </div>
                        <div class="author-box-job">
                            @if(Auth::user()->is_admin == 1)
                            <h6>Administrator</h6>
                            @else
                            <h6>Cashier</h6>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="card card-primary">
                <div class="card-body">
                    <ul class="nav nav-tabs" id="myTab2" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active show" id="home-tab2" data-toggle="tab" href="#home2" role="tab" aria-controls="home" aria-selected="true">Ubah Data Diri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab2" data-toggle="tab" href="#profile2" role="tab" aria-controls="profile" aria-selected="false">Ubah Password</a>
                        </li>
                    </ul>
                    <div class="tab-content tab-bordered" id="myTab3Content">
                        <div class="tab-pane fade active show" id="home2" role="tabpanel" aria-labelledby="home-tab2">
                            <form id="data-user" method="post">
                                <div class="form-group">
                                    <label for="Nama">Nama <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="Nama" name="nama" value="{{ Auth::user()->nama }}" required>
                                </div>
                                <div class="form-group">
                                    <label for="Email">Email <span class="text-danger">*</span></label>
                                    <input type="email" class="form-control" id="Email" name="email" value="{{ Auth::user()->email }}" required>
                                </div>
                                <div class="form-group">
                                    <label for="Usernamae">Username <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="Usernamae" name="username" value="{{ Auth::user()->username }}" required>
                                </div>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary" id="tombol-simpan-data"><i class="fas fa-file mr-1"></i>Simpan Perubahan</button>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane fade" id="profile2" role="tabpanel" aria-labelledby="profile-tab2">
                            <form id="data-password" method="post">
                                <div class="form-group">
                                    <label for="Password_lama">Password Lama <span class="text-danger">*</span></label>
                                    <input type="password" class="form-control" id="Password_lama" name="password_lama" tabindex="1" required autofocus>
                                </div>
                                <div class="form-group">
                                    <label for="Password_baru">Password Baru <span class="text-danger">*</span></label>
                                    <input type="password" class="form-control" id="Password_baru" name="password_baru" tabindex="1" required>
                                </div>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary" id="tombol-simpan-password"><i class="fas fa-file mr-1"></i>Simpan Perubahan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
<script src="{{ asset('js/jquery.form-validator.min.js')}}"></script>
@section('scripts')

<script>
    $(document).ready(function() {

        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('#data-user').on('submit', function(e) {
                e.preventDefault();
                $('#tombol-simpan-data').html('Mengirim...');
                $.ajax({
                    data: $('#data-user').serialize(),
                    url: "{{ route('profile.store') }}",
                    type: "POST",
                    dataType: 'json',

                    success: function(response) {
                        $('#tombol-simpan-data').html('<i class="fas fa-file mr-1"></i>Simpan Perubahan');
                        Swal.fire({
                            title: response.title,
                            text: response.message,
                            icon: response.icon,
                        })
                    },
                    error: function(response) {
                        console.log('Error:', response);
                        $('#tombol-simpan-data').html('<i class="fas fa-file mr-1"></i>Simpan Perubahan');
                    }
                })
            })

            $('#data-password').on('submit', function(e) {
                e.preventDefault();
                $('#tombol-simpan-password').html('Mengirim...');
                $.ajax({
                    data: $('#data-password').serialize(),
                    url: "{{ route('profile.store') }}/{{ Auth::id() }}",
                    type: "PUT",
                    dataType: 'json',

                    success: function(response) {
                        $('#data-password :input').val('');
                        $('#tombol-simpan-password').html('<i class="fas fa-file mr-1"></i>Simpan Perubahan');
                        Swal.fire({
                            title: response.title,
                            text: response.message,
                            icon: response.icon,
                        })
                    },
                    error: function(response) {
                        console.log('Error:', response);
                        $('#tombol-simpan-password').html('<i class="fas fa-file mr-1"></i>Simpan Perubahan');
                    }
                })
            })

        });
    });
</script>


@endsection