routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
  return view('login');
});

Route::resource('auth', 'App\Http\Controllers\AuthController');
Route::middleware(['auth', 'isAdmin:1,0'])->group(function () {

  Route::prefix('menu/')->group(function () {
    Route::resource('home', 'App\Http\Controllers\DashboardController');
    Route::resource('profile', 'App\Http\Controllers\ProfileController');
    Route::resource('penarikan_barang', 'App\Http\Controllers\PenarikanBarangController');
    Route::resource('pengajuan_barang', 'App\Http\Controllers\PengajuanBarangController');

    Route::prefix('master_data/')->group(function () {
      Route::resource('produk', 'App\Http\Controllers\ProdukController');
      Route::resource('barang', 'App\Http\Controllers\BarangController');
      Route::resource('pemasok', 'App\Http\Controllers\PemasokController');
      Route::resource('pelanggan', 'App\Http\Controllers\PelangganController');
    });

    Route::prefix('transaksi/')->group(function () {
      Route::resource('pembelian', 'App\Http\Controllers\PembelianController');
      Route::resource('penjualan', 'App\Http\Controllers\PenjualanController');
    });

    Route::prefix('laporan/')->group(function () {
      Route::resource('laporan_pembelian', 'App\Http\Controllers\LaporanPembelianController');
      Route::resource('laporan_penjualan', 'App\Http\Controllers\LaporanPenjualanController');
    });

    Route::get('logout', function () {
      Auth::logout();
      return redirect('auth');
    });
  });

  Route::prefix('admin/user_manage/')->group(function () {
    Route::middleware(['isAdmin:1'])->group(function () {
      Route::resource('account', 'App\Http\Controllers\UserController');
      Route::resource('access', 'App\Http\Controllers\AccessController');
    });
  });
});

app/Models/PengajuanBarang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class PengajuanBarang extends Model
{
    use HasFactory;

    protected $table = 'pengajuan_barangs';

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($post) {
            $post->{$post->getKeyName()} = (string) Str::uuid();
        });
    }

    public function getIncrementing()
    {
        return false;
    }

    public function getKeyType()
    {
        return 'string';
    }

    protected $fillable = [
        'pelanggan_id', 'tanggal_pengajuan', 'terpenuhi','qty','nama_barang' 
    ];

    public function Pelanggan()
    {
        return $this->belongsTo('App\Models\Pelanggan', 'pelanggan_id', 'id');
    }
}

app/Http/Controllers/PengajuanBarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;

use App\Models\Pelanggan;
use App\Models\PengajuanBarang;
use Yajra\DataTables\DataTables;

use Maatwebsite\Excel\Facades\Excel;
use App\Exports\PengajuanBarangExport;
use App\Models\Logging;
use PDF;

class PengajuanBarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(Request $request)
    {
        $data_pengajuan = DB::table(DB::raw('pengajuan_barangs, (SELECT @rownum := 0) r'))
        ->select('pengajuan_barangs.*', DB::raw('@rownum := @rownum + 1 AS rownum'))->get();
        if ($request->ajax()) {
            return DataTables::of($data_pengajuan)
                ->addColumn('action', function ($row) {
                    $btn = '<div class="dropdown d-inline">';
                    $btn = $btn . '<button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Manage</button>';
                    $btn = $btn . '<div class="dropdown-menu" x-placement="bottom-start" will-change: transform;">';
                    $btn = $btn . '<a class="dropdown-item has-icon editPengajuanBarang" href="javascript:void(0)"  data-id="' . $row->id . '" data-pelanggan_id="' . $row->pelanggan_id . '" data-nama_barang="' . $row->nama_barang . '" data-tanggal_pengajuan="' . $row->tanggal_pengajuan . '" data-qty="' . $row->qty . '"><i class="far fa-edit"></i> Edit</a>';
                    $btn = $btn . '<a class="dropdown-item has-icon deletePengajuanBarang" href="javascript:void(0)" data-id="' . $row->id . '"><i class="fas fa-trash"></i> Hapus</a>';
                    $btn = $btn . '</div>';
                    $btn = $btn . '</div>';
                    return $btn;
                })
                ->editColumn('pelanggan_id', function ($row) {
                    $pelanggan = Pelanggan::where('id', $row->pelanggan_id)->first();
                    return $pelanggan->nama;
                })
                ->editColumn('terpenuhi', function ($row) {
                    if ($row->terpenuhi == 1 && Auth::user()->is_admin == 1) {
                        $toggle = '<label class="custom-switch">';
                        $toggle = $toggle . '<input type="checkbox" name="terpenuhi_status" checked class="custom-switch-input" data-id = "'. $row->id . '" data-terpenuhi = "' . $row->terpenuhi . '">';
                        $toggle = $toggle . '<span class="custom-switch-indicator"></span>';
                        $toggle = $toggle . '</label>';
                    } elseif($row->terpenuhi == 0 && Auth::user()->is_admin == 1){
                        $toggle = '<label class="custom-switch">';
                        $toggle = $toggle . '<input type="checkbox" name="terpenuhi_status" class="custom-switch-input" data-id = "' . $row->id . '" data-terpenuhi = "' . $row->terpenuhi . '">';
                        $toggle = $toggle . '<span class="custom-switch-indicator"></span>';
                        $toggle = $toggle . '</label>';
                    } else if ($row->terpenuhi == 1 && Auth::user()->is_admin == 0) {
                        $toggle = '<label class="custom-switch">';
                        $toggle = $toggle . '<input type="checkbox" disabled="" checked class="custom-switch-input">';
                        $toggle = $toggle . '<span class="custom-switch-indicator"></span>';
                        $toggle = $toggle . '</label>';
                    } else {
                        $toggle = '<label class="custom-switch">';
                        $toggle = $toggle . '<input type="checkbox" disabled="" class="custom-switch-input">';
                        $toggle = $toggle . '<span class="custom-switch-indicator"></span>';
                        $toggle = $toggle . '</label>';
                    }
                    return $toggle;
                })
                ->rawColumns(['action', 'terpenuhi'])
                ->make(true);
        }
        return view('pengajuan_barang.index', ['title' => "Pengajuan Barang"]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return Excel::download(new PengajuanBarangExport, 'penarikan_barang-' . time() . '-' . rand() . '.xlsx');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (empty($request->id)) {
            $penarikan_barang = new PengajuanBarang();
            $penarikan_barang->id = Str::uuid();
            $penarikan_barang->pelanggan_id = $request->pelanggan_id;
            $penarikan_barang->nama_barang = $request->nama_barang;
            $penarikan_barang->tanggal_pengajuan = $request->tanggal_pengajuan;
            $penarikan_barang->qty = $request->qty;
            $penarikan_barang->save();
            return response()->json(['title' => 'Create Success', 'message' => 'Data Berhasil Disimpan', 200]);
        } else {
            PengajuanBarang::where('id', $request->id)->update($request->all());
            return response()->json(['title' => 'Edit Success', 'message' => 'Data Berhasil Diubah', 200]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = PengajuanBarang::get();
        $pdf = PDF::loadView('pengajuan_barang.export_pdf', compact('data'));
        return $pdf->stream('pengajuan_barang-' . time() . '-' . rand() . '.pdf');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        if ($request->terpenuhi == 1) {
            PengajuanBarang::where('id', $request->id)->update(['terpenuhi' => 0]);
        } else {
            PengajuanBarang::where('id', $request->id)->update(['terpenuhi' => 1]);
        }
        return response()->json(['title' => 'Change Success', 'message' => 'Status Berhasil Diubah', 200]);
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        PengajuanBarang::find($id)->delete();
        return response()->json(['title' => 'Delete Success', 'message' => 'Data Berhasil Dihapus', 200]);
    }
}

resources/views/pengajuan_barang/export_pdf.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8">
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <style type="text/css">
  html {
   font-family: "Arial", sans-serif;
   margin: 0;
   padding: 0;
  }

  .header {
   background-color: #d3eafc;
   padding: 40px 70px;
  }

  .body {
   padding: 20px 70px;
  }

  /* Text */
  .text-30 {
   font-size: 30px;
  }

  .text-20 {
   font-size: 20px;
  }

  .text-18 {
   font-size: 18px;
  }

  .text-16 {
   font-size: 16px;
  }

  .text-14 {
   font-size: 14px;
  }

  .text-12 {
   font-size: 12px;
  }

  .text-10 {
   font-size: 10px;
  }

  .font-bold {
   font-weight: bold;
  }

  .text-left {
   text-align: left;
  }

  .text-right {
   text-align: right;
  }

  .text-center {
   text-align: center;
   margin-right: 50px;
  }

  .txt-dark {
   color: #5b5b5b;
  }

  .txt-dark2 {
   color: #1d1d1d;
  }

  .txt-blue {
   color: #2a4df1;
  }

  .txt-light {
   color: #acacac;
  }

  .txt-green {
   color: #19d895;
  }

  p {
   margin: 0;
  }

  .d-block {
   display: block;
  }

  .w-100 {
   width: 100%;
  }

  .mt-2 {
   margin-top: 10px;
  }

  .mb-1 {
   margin-bottom: 5px;
  }

  .mb-4 {
   margin-bottom: 20px;
  }

  .pt-30 {
   padding-top: 30px;
  }

  .pt-15 {
   padding-top: 15px;
  }

  .pt-5 {
   padding-top: 5px;
  }

  .pb-5 {
   padding-bottom: 5px;
  }

  table {
   border-collapse: collapse;
  }

  thead tr td {
   border-bottom: 0.5px solid #d9dbe4;
   color: #7e94f6;
   font-size: 12px;
   padding: 5px;
   text-transform: uppercase;
  }

  tbody tr td {
   padding: 7px;
  }

  .border-top-foot {
   border-top: 0.5px solid #d9dbe4;
  }

  .mr-20 {
   margin-right: 20px;
  }

  ul {
   padding: 0;
  }

  ul li {
   list-style-type: none;
  }

  .w-300p {
   width: 300px;
  }
 </style>
</head>

<body>
 <div class="header">
  <table class="w-100">
   <tr>
    <td class="text-center text-20 txt-blue font-bold">LAPORAN DATA PENGAJUAN BARANG</td>
    <td class="text-right text-12 txt-blue">Oleh {{ Auth::user()->nama }}</td>
   </tr>
  </table>
 </div>

 <div class="body">
  <table class="w-100 mb-4">
   <thead>
    <tr>
     <td>Nama Pengaju</td>
     <td>Nama Barang</td>
     <td>Tanggal Pengajuan</td>
     <td>Qty</td>
     <td>Status</td>
    </tr>
   </thead>
   <tbody>
    @foreach($data as $dt)
    <tr>
     <td class="txt-dark text-10">{{ $dt->Pelanggan->nama }}</td>
     <td class="txt-dark text-10">{{ $dt->nama_barang }}</td>
     <td class="txt-dark text-10">{{ $dt->tanggal_pengajuan }}</td>
     <td class="txt-dark text-10">{{ $dt->qty }}</td>
     @if($dt->terpenuhi == 1)
     <td class="txt-dark text-10">TERPENUHI</td>
     @else
     <td class="txt-dark text-10">TIDAK TERPENUHI</td>
     @endif
    </tr>
    @endforeach

   </tbody>
  </table>
</body>

</html>

resources/views/pengajuan_barang/index.blade.php
@extends('templates/master')
@section('css')
<link rel="stylesheet" href="{{ asset('css/datepicker.min.css') }}">
@endsection
@section('content')

<div class="section-header">
 <h1>{{ $title }}</h1>
 <div class="section-header-button">
  <a href="javascript:void(0)" id="tombol-tambah" class="btn btn-primary"><i class="fas fa-plus-circle mr-1"></i>Pengajuan Barang</a>
 </div>
 <div class="section-header-breadcrumb">
  <div class="breadcrumb-item active">Menu</div>
  <div class="breadcrumb-item"><a href="javascript:void(0)">{{ $title }}</a></div>
 </div>
</div>

<div class="section-body">
 <div class="card">
  <div class="card-body">
  <a href="{{ url('menu/pengajuan_barang') }}/{{ Auth::id() }}/edit" class="btn btn-sm btn-danger mb-2"><i class="far fa-file-pdf mr-1"></i>PDF</a>
  <a href="{{ url('menu/pengajuan_barang/create') }}" class="btn btn-sm btn-success mb-2"><i class="far fa-file-excel mr-1"></i>Excel</a>
   <div class="table-responsive">
    <table class="table table-bordered table-striped table-hover" id="data-table" style="width:100%">
     <thead class="text-dark bg-light">
      <tr>
       <th width="5%">No</th>
       <th>Nama Pengaju</th>
       <th>Nama Barang</th>
       <th>Tanggal Pengajuan</th>
       <th>Qty</th>
       <th>Terpenuhi</th>
       <th width="10%">Action</th>
      </tr>
     </thead>
     <tbody class="text-dark"></tbody>
    </table>
   </div>
  </div>
 </div>
</div>

@endsection
@section('scripts')
<script src="{{ asset('js/datepicker.min.js') }}"></script>
@include('pengajuan_barang/modal')
<script>
 $(document).ready(function() {
  $('#Pengajuan_barang_sidebar').parent().addClass('active');
  $('#Pengajuan_barang_sidebar').parent().parent().parent().addClass('active');

  $('.date').datepicker({
   format: 'yyyy-mm-dd'
  });

  $(function() {
   $.ajaxSetup({
    headers: {
     'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
   });
   let table = $('#data-table').DataTable({
    processing: true,
    serverSide: true,
    responsive: true,
    ajax: "{{ route('pengajuan_barang.index') }}",
    columns: [{
      data: 'rownum',
      name: 'rownum',
      searchable: false
     },
     {
      data: 'pelanggan_id',
      name: 'pelanggan_id'
     },
     {
      data: 'nama_barang',
      name: 'nama_barang'
     },
     {
      data: 'tanggal_pengajuan',
      name: 'tanggal_pengajuan'
     },
     {
      data: 'qty',
      name: 'qty'
     },
     {
      data: 'terpenuhi',
      name: 'terpenuhi'
     },
     {
      data: 'action',
      name: 'action',
      orderable: false,
      searchable: false
     },
    ],
   });

   $('#tombol-tambah').click(function() {
    $('#button-simpan').val("create-post");
    $('#Id').val('');
    $('#form-tambah-edit').trigger("reset");
    $('#myModalLabel').text("Tambah Pengajuan Barang");
    $('#tambah-edit-modal').modal('show');
   });

   if ($("#form-tambah-edit").length > 0) {
    $("#form-tambah-edit").validate({
     messages: {
      pelanggan_id: "Nama pengaju tidak boleh kosong",
      nama_barang: "Nama barang tidak boleh kosong",
      tanggal_pengajuan: "Tanggal pengajuan tidak boleh kosong",
      qty: "Qty tidak boleh kosong",
     },
     errorPlacement: function(error, element) {
      let name = element.attr("name");
      $("#" + name + "_error").html(error);
     },

     submitHandler: function(form) {
      $('#tombol-simpan').html('Mengirim..');
      let dataPenarikan = new FormData(form);
      $.ajax({
       data: dataPenarikan,
       url: "{{ route('pengajuan_barang.store') }}",
       type: "POST",
       dataType: 'json',
       contentType: false,
       cache: false,
       processData: false,
       success: function(response) {
        $('#tombol-simpan').html('Simpan');
        if (response.icon == 'error') {
         $('#tambah-edit-modal').modal('show');
         iziToast.error({
          title: response.title,
          message: response.message,
          position: 'topRight',
         });
        } else {
         $('#form-tambah-edit').trigger("reset");
         $('#tambah-edit-modal').modal('hide');
         table.draw();
         iziToast.success({
          title: response.title,
          message: response.message,
          position: 'topRight',
         });
        }
       },
       error: function(response) {
        console.log('Error:', response);
        $('#tombol-simpan').html('Simpan');
       }
      });
     }
    });
   }

   $(document).on('click', 'input[name="terpenuhi_status"]', function() {
    let data_terpenuhi = {
     id: $(this).attr('data-id'),
     terpenuhi: $(this).attr('data-terpenuhi')
    }

    iziToast.success({
     title: 'Change Success',
     message: 'Status terpenuhi Berhasil Diubah',
     position: 'topRight',
    });
    $.ajax({
     data: data_terpenuhi,
     url: "{{ route('pengajuan_barang.store') }}/{{ Auth::id() }}",
     method: "PUT",
     dataType: "json",
     success: function(response) {
      table.draw();
     },
     error: function(response) {
      console.log("Error: ", response)
     }
    })
    alert(data);
   })

   $(document).on('click', '.editPengajuanBarang', function() {
    $('#myModalLabel').text("Edit Pengajuan Barang");
    $('#tombol-simpan').val("edit-post");
    $('#tambah-edit-modal').modal('show');

    let id = $(this).attr("data-id");
    let pelanggan_id = $(this).attr("data-pelanggan_id");
    let nama_barang = $(this).attr("data-nama_barang");
    let tanggal_pengajuan = $(this).attr("data-tanggal_pengajuan");
    let qty = $(this).attr("data-qty");

    $('.modal-body #Id').val(id);
    $('.modal-body #Pelanggan_id').val(pelanggan_id);
    $('.modal-body #Nama_barang').val(nama_barang);
    $('.modal-body #Tanggal_pengajuan').val(tanggal_pengajuan);
    $('.modal-body #Qty').val(qty);

   });

   $(document).on('click', '.deletePengajuanBarang', function() {
    let id = $(this).attr("data-id");
    iziToast.question({
     timeout: 20000,
     close: false,
     overlay: true,
     displayMode: 'once',
     id: 'question',
     zindex: 999,
     title: 'Yakin?',
     message: 'Data akan terhapus.',
     position: 'center',
     buttons: [
      ['<button><b>Ya, </b>Hapus</button>', function(instance, toast) {

       $.ajax({
        type: "DELETE",
        url: "{{ route('pengajuan_barang.store') }}/" + id,
        success: function(response) {
         table.draw();
         iziToast.success({
          title: response.title,
          message: response.message,
          position: 'topRight',
         });
        },
        error: function(response) {
         console.log('Error:', response);
         $('#tombol-simpan').html('Simpan');
        }
       });

       instance.hide({
        transitionOut: 'fadeOut'
       }, toast, 'button');

      }, true],
      ['<button>Batal</button>', function(instance, toast) {

       instance.hide({
        transitionOut: 'fadeOut'
       }, toast, 'button');

      }],
     ],
    });
   });

  });
 });
</script>

@endsection

resources/views/pengajuan_barang/modal.blade.php
<div class="modal fade" id="tambah-edit-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" class="needs-validation" novalidate="" id="form-tambah-edit" name="form-tambah-edit">
          <input type="hidden" name="id" id="Id" value="">
          <div class="form-group">
            <label for="pelanggan_id">Nama Pengaju <span class="text-danger">*</span></label>
            <select name="pelanggan_id" class="form-control" id="Pelanggan_id" required tabindex="1">
              <option value="">Pilih..</option>
              @foreach(App\Models\Pelanggan::orderBy('kode_pelanggan')->get() as $pl)
              <option value="{{ $pl->id }}">{{ $pl->kode_pelanggan }} - {{ $pl->nama }}</option>
              @endforeach
            </select>
            <div class="invalid-feedback" id="pelanggan_id_error"></div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="nama_barang">Nama Barang</label>
              <input type="text" class="form-control" name="nama_barang" id="Nama_barang" required tabindex="2">
              <div class="invalid-feedback" id="nama_barang_error"></div>
            </div>
            <div class="form-group col-md-6">
              <label for="nama_barang">Qty</label>
              <input type="number" class="form-control" name="qty" id="Qty" required tabindex="3">
              <div class="invalid-feedback" id="qty_error"></div>
            </div>
          </div>
          <div class="form-group">
            <label for="Tanggal_pengajuan">Tanggal Pengajuan <span class="text-danger">*</span></label>
            <input type="date" class="form-control" name="tanggal_pengajuan" value="{{ date('d/M/Y') }}" tabindex="4" id="Tanggal_pengajuan" autocomplete="off" required>
            <div class="invalid-feedback" id="tanggal_pengajuan_error"></div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary btn-block" id="tombol-simpan" tabindex="5">Simpan</button>
        <button type="submit" class="btn btn-light" data-dismiss="modal">Close</button>
      </div>
      </form>
    </div>
  </div>
</div>