routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
  return view('login');
});

Route::resource('auth', 'App\Http\Controllers\AuthController');
Route::middleware(['auth', 'isAdmin:1,0'])->group(function () {

  Route::prefix('menu/')->group(function () {
    Route::resource('home', 'App\Http\Controllers\DashboardController');
    Route::resource('profile', 'App\Http\Controllers\ProfileController');
    Route::resource('penarikan_barang', 'App\Http\Controllers\PenarikanBarangController');
    Route::resource('pengajuan_barang', 'App\Http\Controllers\PengajuanBarangController');

    Route::prefix('master_data/')->group(function () {
      Route::resource('produk', 'App\Http\Controllers\ProdukController');
      Route::resource('barang', 'App\Http\Controllers\BarangController');
      Route::resource('pemasok', 'App\Http\Controllers\PemasokController');
      Route::resource('pelanggan', 'App\Http\Controllers\PelangganController');
    });

    Route::prefix('transaksi/')->group(function () {
      Route::resource('pembelian', 'App\Http\Controllers\PembelianController');
      Route::resource('penjualan', 'App\Http\Controllers\PenjualanController');
    });

    Route::prefix('laporan/')->group(function () {
      Route::resource('laporan_pembelian', 'App\Http\Controllers\LaporanPembelianController');
      Route::resource('laporan_penjualan', 'App\Http\Controllers\LaporanPenjualanController');
    });

    Route::get('logout', function () {
      Auth::logout();
      return redirect('auth');
    });
  });

  Route::prefix('admin/user_manage/')->group(function () {
    Route::middleware(['isAdmin:1'])->group(function () {
      Route::resource('account', 'App\Http\Controllers\UserController');
      Route::resource('access', 'App\Http\Controllers\AccessController');
    });
  });
});

app/Models/Barang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Barang extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($post) {
            $post->{$post->getKeyName()} = (string) Str::uuid();
        });
    }

    public function getIncrementing()
    {
        return false;
    }

    public function getKeyType()
    {
        return 'string';
    }

    protected $fillable = [
        'kode_barang', 'produk_id', 'nama_barang', 'satuan', 'harga_jual', 'stok', 'user_id'
    ];

    public function Produks()
    {
        return $this->belongsTo('App\Models\Produk', 'produk_id', 'id');
    }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

use App\Models\Barang;
use App\Models\Acces;
use Yajra\DataTables\DataTables;

class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $checkAccess = Acces::where('user_id', Auth::id())->first();
        if ($checkAccess->kelola_barang == 1 && Auth::check() == true) {
            $lastId = Barang::select('kode_barang')->orderBy('kode_barang', 'desc')->first();
            $kode = ($lastId == null ? 'B0000001' : sprintf('B%07d', substr($lastId->kode_barang, 1) + 1));

            if ($request->ajax()) {
                DB::statement(DB::raw('set @rownum := 0'));
                $barang = Barang::select(DB::raw('@rownum := 0 r'))
                    ->select(DB::raw('@rownum := @rownum + 1 AS rownum'), 'barangs.*');
                return DataTables::of($barang)
                    ->addColumn('action', function ($row) {
                        $btn = '<div class="dropdown d-inline">';
                        $btn = $btn . '<button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Manage</button>';
                        $btn = $btn . '<div class="dropdown-menu" x-placement="bottom-start" will-change: transform;">';
                        $btn = $btn . '<a class="dropdown-item has-icon editBarang" href="javascript:void(0)"  data-id="' . $row->id . '" data-kode_barang="' . $row->kode_barang . '" data-produk_id="' . $row->produk_id . '" data-nama_barang="' . $row->nama_barang . '" data-satuan="' . $row->satuan . '" data-harga_jual="' . $row->harga_jual . '" data-stok="' . $row->stok . '"><i class="far fa-edit"></i> Edit</a>';
                        $btn = $btn . '<a class="dropdown-item has-icon deleteBarang" href="javascript:void(0)" data-id="' . $row->id . '" data-nama_barang="' . $row->nama_barang . '"><i class="fas fa-trash"></i> Hapus</a>';
                        $btn = $btn . '</div>';
                        $btn = $btn . '</div>';
                        return $btn;
                    })
                    ->editColumn('produk_id', function ($row) {
                        return $row->Produks->nama_produk;
                    })
                    ->editColumn('harga_jual', function ($row) {
                        return 'Rp. ' . number_format($row->harga_jual, 0);
                    })
                    ->rawColumns(['action'])
                    ->make(true);
            }

            return view('barang.index', ['title' => "Barang", 'kode' => $kode]);
        } else {
            return back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $checkAccess = Acces::where('user_id', Auth::id())->first();
        if ($checkAccess->kelola_barang == 1 && Auth::check() == true) {
            if (empty($request->id)) {
                $check_kode_barang = Barang::where('kode_barang', $request->kode_barang)->count();
                if ($check_kode_barang != 0) {
                    return response()->json(['icon' => 'error', 'title' => 'Create Fail', 'message' => 'Kode Barang sudah tersedia harap refresh terlebih dahulu', 401]);
                } else {
                    $barang = new barang;
                    $barang->id = Str::uuid();
                    $barang->kode_barang = $request->kode_barang;
                    $barang->produk_id = $request->produk_id;
                    $barang->nama_barang = $request->nama_barang;
                    $barang->satuan = $request->satuan;
                    $barang->harga_jual = $request->harga_jual;
                    $barang->stok = $request->stok;
                    $barang->save();
                    return response()->json(['title' => 'Create Success', 'message' => 'Data Berhasil Disimpan', 200]);
                }
            } else {
                $barang = Barang::where('id', $request->id)->update($request->all());
                return response()->json(['title' => 'Edit Success', 'message' => 'Data Berhasil Diubah', 200]);
            }
        } else {
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $checkAccess = Acces::where('user_id', Auth::id())->first();
        if ($checkAccess->kelola_barang == 1 && Auth::check() == true) {
            Barang::find($id)->delete();
            return response()->json(['title' => 'Delete Success', 'message' => 'Data Berhasil Dihapus', 200]);
        } else {
            return back();
        }
    }
}

resources/views/barang/index.blade.php
@extends('templates/master')
@section('content')

<div class="section-header">
  <h1>{{ $title }}</h1>
  <div class="section-header-button">
    <a href="javascript:void(0)" id="tombol-tambah" class="btn btn-primary"><i class="fas fa-plus-circle mr-1"></i>Data Barang</a>
  </div>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item active">Menu</div>
    <div class="breadcrumb-item">Data Master</div>
    <div class="breadcrumb-item"><a href="javascript:void(0)">{{ $title }}</a></div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover" id="data-table" style="width:100%">
              <thead class="text-dark bg-light">
                <tr>
                  <th>No</th>
                  <th>Kode Barang</th>
                  <th>Produk</th>
                  <th>Nama Barang</th>
                  <th>Satuan</th>
                  <th>Harga</th>
                  <th>Stok</th>
                  <th width="10%">Action</th>
                </tr>
              </thead>
              <tbody class="text-dark"></tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection
@section('scripts')
@include('barang/modal')
<script>
  $(document).ready(function() {
    $('#Barang_sidebar').parent().addClass('active');
    $('#Barang_sidebar').parent().parent().parent().addClass('active');

    $(function() {
      $.ajaxSetup({
        headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
      });
      let table = $('#data-table').DataTable({
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: "{{ route('barang.index') }}",
        columns: [{
            data: 'rownum',
            name: 'rownum'
          }, {
            data: 'kode_barang',
            name: 'kode_barang'
          },
          {
            data: 'produk_id',
            name: 'produk_id'
          },
          {
            data: 'nama_barang',
            name: 'nama_barang'
          },
          {
            data: 'satuan',
            name: 'satuan'
          },
          {
            data: 'harga_jual',
            name: 'harga_jual'
          },
          {
            data: 'stok',
            name: 'stok'
          },
          {
            data: 'action',
            name: 'action',
            orderable: false,
            searchable: false
          },
        ],
      });

      $('#tombol-tambah').click(function() {
        // let foo = <?= json_encode($lastId = App\Models\Barang::select('kode_barang')->orderBy('kode_barang', 'desc')->first()) ?>;
        // let kode_barang = <?= json_encode(($lastId == null ? 'B0000001' : sprintf('B%07d', substr($lastId->kode_barang, 1) + 1))) ?>;
        // alert(kode_barang);
        $('#button-simpan').val("create-post");
        $('#Id').val('');
        $('#form-tambah-edit').trigger("reset");
        $('#myModalLabel').text("Tambah Barang");
        $('#tambah-edit-modal').modal('show');
      });

      if ($("#form-tambah-edit").length > 0) {
        $("#form-tambah-edit").validate({
          messages: {
            produk_id: "Produk tidak boleh kosong",
            nama_barang: "Nama barang tidak boleh kosong",
            satuan: "Satuan tidak boleh kosong",
            stok: "Stok tidak boleh kosong",
            harga_jual: {
              required: "Harga tidak boleh kosong",
              min: "Harga minimal Rp.500",
            },
          },
          errorPlacement: function(error, element) {
            let name = element.attr("name");
            $("#" + name + "_error").html(error);
          },

          submitHandler: function(form) {
            $('#tombol-simpan').html('Mengirim..');

            $.ajax({
              data: $('#form-tambah-edit').serialize(),
              url: "{{ route('barang.store') }}",
              type: "POST",
              dataType: 'json',
              success: function(response) {
                $('#tombol-simpan').html('Simpan');
                if (response.icon == 'error') {
                  $('#tambah-edit-modal').modal('show');
                  iziToast.error({
                    title: response.title,
                    message: response.message,
                    position: 'topRight',
                  });
                } else {
                  $('#form-tambah-edit').trigger("reset");
                  $('#tambah-edit-modal').modal('hide');
                  table.draw();
                  iziToast.success({
                    title: response.title,
                    message: response.message,
                    position: 'topRight',
                  });
                }
              },
              error: function(response) {
                console.log('Error:', response);
                $('#tombol-simpan').html('Simpan');
              }
            });
          }
        });
      }

      $(document).on('click', '.editBarang', function() {
        $('#myModalLabel').text("Edit Barang");
        $('#tombol-simpan').val("edit-post");
        $('#tambah-edit-modal').modal('show');

        let id = $(this).attr("data-id");
        let kode_barang = $(this).attr("data-kode_barang");
        let produk_id = $(this).attr("data-produk_id");
        let nama_barang = $(this).attr("data-nama_barang");
        let satuan = $(this).attr("data-satuan");
        let harga_jual = $(this).attr("data-harga_jual");
        let stok = $(this).attr("data-stok");

        $('.modal-body #Id').val(id);
        $('.modal-body #kode_barang').val(kode_barang);
        $('.modal-body #Produk_id').val(produk_id);
        $('.modal-body #Nama_barang').val(nama_barang);
        $('.modal-body #Satuan').val(satuan);
        $('.modal-body #Harga_jual').val(harga_jual);
        $('.modal-body #Stok').val(stok);
      });

      $(document).on('click', '.deleteBarang', function() {
        let id = $(this).attr("data-id");
        let nama_barang = $(this).attr("data-nama_barang");
        iziToast.question({
          timeout: 20000,
          close: false,
          overlay: true,
          displayMode: 'once',
          id: 'question',
          zindex: 999,
          title: 'Yakin?',
          message: 'Data "' + nama_barang + '" akan terhapus.',
          position: 'center',
          buttons: [
            ['<button><b>Ya, </b>Hapus</button>', function(instance, toast) {

              $.ajax({
                type: "DELETE",
                url: "{{ route('barang.store') }}/" + id,
                success: function(response) {
                  table.draw();
                  iziToast.success({
                    title: response.title,
                    message: response.message,
                    position: 'topRight',
                  });
                },
                error: function(response) {
                  console.log('Error:', response);
                  $('#tombol-simpan').html('Simpan');
                }
              });

              instance.hide({
                transitionOut: 'fadeOut'
              }, toast, 'button');

            }, true],
            ['<button>Batal</button>', function(instance, toast) {

              instance.hide({
                transitionOut: 'fadeOut'
              }, toast, 'button');

            }],
          ],
        });

      });

    });
  });
</script>

@endsection

resources/views/barang/modal.blade.php
<div class="modal fade" id="tambah-edit-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" class="needs-validation" novalidate="" id="form-tambah-edit" name="form-tambah-edit">
          <input type="hidden" name="id" id="Id" value="">
          <div class="form-row">
            <div class="form-group col-md-4">
              <label for="kode_barang">Kode Barang</label>
              <input id="kode_barang" type="text" class="form-control" value="{{ $kode }}" name="kode_barang" tabindex="1" readonly>
            </div>
            <div class="form-group col-md-8">
              <label for="Produk_id">Nama Produk <span class="text-danger">*</span> </label>
              @php $produk = \App\Models\Produk::get() @endphp
              <select id="Produk_id" type="text" class="form-control custom-select" name="produk_id" maxlength="50" tabindex="1" required>
                <option value="">Pilih..</option>
                @foreach($produk as $pd)
                <option value="{{ $pd->id }}">{{ $pd->nama_produk }}</option>
                @endforeach
              </select>
              <div class="invalid-feedback" id="produk_id_error"></div>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-7">
              <label for="nama_barang">Nama Barang <span class="text-danger">*</span></label>
              <input id="Nama_barang" type="text" class="form-control" name="nama_barang" tabindex="2" required>
              <div class="invalid-feedback" id="nama_barang_error"></div>
            </div>
            <div class="form-group col-md-5">
              <label for="Satuan">Satuan <span class="text-danger">*</span></label>
              <input id="Satuan" class="form-control" name="satuan" tabindex="3" required>
              <div class="invalid-feedback" id="satuan_error"></div>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-7">
              <label for="Harga_jual">Harga jual <span class="text-danger">*</span></label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <div class="input-group-text">
                    Rp
                  </div>
                </div>
                <input type="number" class="form-control" id="Harga_jual" name="harga_jual" autocomplete="off" min="500" tabindex="4" required>
                <div class="invalid-feedback" id="harga_jual_error" style="margin-left: 55px;"></div>
              </div>
            </div>

            <div class="form-group col-md-5">
              <label for="Stok">Stok <span class="text-danger">*</span></label>
              <input type="number" class="form-control" name="stok" id="Stok" min="1" autocomplete="off" tabindex="5" required>
              <div class="invalid-feedback" id="stok_error"></div>
            </div>
          </div>

      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary btn-block" id="tombol-simpan" tabindex="6">Simpan</button>
        <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
      </div>
      </form>
    </div>
  </div>
</div>